# Generated by Django 5.2.12 on 2026-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemember',
            name='display_name',
            field=models.CharField(blank=True, help_text="Friendly name shown in the UI (e.g. 'Zach'). Falls back to name if blank.", max_length=255),
        ),
        migrations.AlterField(
            model_name='voicemember',
            name='name',
            field=models.CharField(help_text='GroupMe user ID — do not edit', max_length=255, unique=True),
        ),
    ]
