# Generated by Django 5.2.12 on 2026-03-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voice', '0002_voicemember_display_name_alter_voicemember_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Trigger word to detect in messages (e.g. 'bbr'). Case-insensitive.", max_length=100)),
                ('bot_id', models.CharField(help_text='GroupMe bot ID used for posting responses.', max_length=255)),
                ('group_id', models.CharField(blank=True, help_text='GroupMe group ID (for reference).', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bot responds to messages.')),
                ('voice_blend', models.BooleanField(default=False, help_text='If True, blend all active voices instead of a specific member.')),
                ('voice', models.ForeignKey(blank=True, help_text='Voice style for responses. Leave blank for plain RAG.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupme_bots', to='voice.voicemember')),
            ],
            options={
                'verbose_name': 'GroupMe Bot',
                'verbose_name_plural': 'GroupMe Bots',
            },
        ),
    ]
