# Generated by Django 5.2.12 on 2026-03-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(help_text='Raw JSON body from the GroupMe callback.')),
                ('sender_type', models.CharField(blank=True, max_length=50)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, max_length=255)),
                ('message_text', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('ignored', 'Ignored'), ('responded', 'Responded'), ('error', 'Error')], default='ignored', max_length=20)),
                ('response_text', models.TextField(blank=True, help_text='Response sent back to GroupMe, if any.')),
                ('error_message', models.TextField(blank=True, help_text='Error details if something went wrong.')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds.', null=True)),
                ('bot', models.ForeignKey(blank=True, help_text='Bot that handled this request, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='groupme.groupmebot')),
            ],
            options={
                'verbose_name': 'Callback Log',
                'verbose_name_plural': 'Callback Logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
