# Generated by Django 5.2.12 on 2026-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0002_callbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmebot',
            name='max_response_length',
            field=models.IntegerField(blank=True, help_text='Max character length for responses. Leave blank for no limit (GroupMe messages are split at 1000 chars automatically).', null=True),
        ),
        migrations.AddField(
            model_name='groupmebot',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Custom system prompt for this bot. Overrides the default RAG prompt. Use this to set personality, constraints, response style, etc.'),
        ),
    ]
