# Generated by Django 5.2.11 on 2026-02-14 17:07

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.JSONField(default=list, help_text='List of keywords to search for')),
                ('is_active', models.BooleanField(default=True)),
                ('crawl_frequency_hours', models.IntegerField(default=24, help_text='How often to crawl this topic (in hours)')),
                ('max_pages_per_crawl', models.IntegerField(default=10, help_text='Maximum pages to crawl per run')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pages_discovered', models.IntegerField(default=0)),
                ('pages_crawled', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='crawler.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('crawl_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='crawler.crawljob')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_pages', to='crawler.topic')),
            ],
            options={
                'ordering': ['-crawled_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('chunk_index', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='crawler.crawledpage')),
            ],
            options={
                'ordering': ['page', 'chunk_index'],
                'unique_together': {('page', 'chunk_index')},
            },
        ),
    ]
