# Generated by Django 5.2.12 on 2026-03-05 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='voice',
            field=models.ForeignKey(blank=True, help_text='Writing voice to use for responses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='voice.voicemember'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='voice_blend',
            field=models.BooleanField(default=False, help_text='If True, blend all active voices instead of a specific member.'),
        ),
    ]
